# Generated by Django 3.2.18 on 2023-08-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id'], 'verbose_name': 'задачу', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='profile',
            name='check_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ManyToManyField(blank=True, through='task.UserTasks', to='task.Profile', verbose_name='Исполнитель'),
        ),
    ]
